[env]
TERM = "xterm-256color"


[font]
size = 13.0

[font.normal]
# family = "Hack Nerd Font Mono"
family = "JetBrainsMono Nerd Font"

[window]
opacity = 0.9875
dynamic_padding = true
decorations = 'None'

[window.dimensions]
columns = 120
lines = 30

[general]
live_config_reload = true

[[keyboard.bindings]]
chars = "\u001Bf"
key = "F"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "B"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bh"
key = "H"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bj"
key = "J"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bk"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bl"
key = "L"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bp"
key = "P"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Ba"
key = "A"
mods = "Command"

# [[keyboard.bindings]]
# chars = "\u001Bw"
# key = "W"
# mods = "Command"

[[keyboard.bindings]]
chars = "\u001B1"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B2"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B3"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B4"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B5"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B6"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B7"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B8"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B9"
key = "Key9"
mods = "Command"

[scrolling]
history = 100000
